version: "3.4"

services:
  php:
    container_name: php
    build:
      context: ./backend
      dockerfile: Dockerfile.local
      args:
        IMAGE_NAME: webfux/php81-fpm
        IMAGE_TAG: 1.0.0
#    restart: on-failure
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      # target /var/app has to be:
      # 1. identically to <root> inside /webserver/.deploy/nginx/conf.d/local.conf
      # 2. identically to Dockerfile.local directive WORKDIR
      - ./backend:/var/app
    # image is alpine base: command => sh -c
    # 1. composer install (requires composer.json)
    # 2. start php-fpm as --allow-to-run-as-root
    command: sh -c "composer install && php-fpm --allow-to-run-as-root"

  webserver:
    container_name: webserver
    build:
      context: ./webserver
      dockerfile: Dockerfile.local
      args:
        IMAGE_NAME: webfux/nginx
        IMAGE_TAG: 1.0.0
#    restart: on-failure
    depends_on:
      - php
      - database
    ports:
      - target: 80
        published: 80
    volumes:
      - ./webserver/.deploy/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf

  database:
    container_name: database
    image: webfux/mariadb:1.0.0
#    restart: on-failure
    env_file:
      - .env
    ports:
      - target: 3306
        published: 3366
    volumes:
      # persist data (inside docker)
      - dbcontainer:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

volumes:
  # persist data (inside docker)
  dbcontainer: