version: "3.4"

services:
  php:
    container_name: php
    build:
      context: ./api
      dockerfile: Dockerfile.local
      args:
        IMAGE_NAME: webfux/php82-fpm
        IMAGE_TAG: 1.0.0
    depends_on:
      - database
    environment:
    # given arguments overwrite configuration in api/.env
      # can also be set in api/.env
      TRUSTED_HOSTS: localhost|api.dev.webfux.io|www.dev.webfux.io
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverVersion=${MYSQL_VERSION}
    volumes:
      - ./api/.deploy/php/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./api/.deploy/php/docker-healthcheck.sh:/usr/local/bin/docker-healthcheck.sh
      # mounted folder has to be identically to nginx directive AND workdir in Dockerfile
      - ./api:/var/app
      # prevent mounting folders outside docker
      - /var/app/vendor
      - /var/app/var
    # cause docker-entrypoint.sh and php-fpm are mounted
    entrypoint: ["docker-entrypoint.sh"]
    command: ["php-fpm"]
    extra_hosts:
      - host.docker.internal:host-gateway

  webserver:
    container_name: webserver
    build:
      context: ./webserver
      dockerfile: Dockerfile.local
      args:
        IMAGE_NAME: webfux/nginx
        IMAGE_TAG: 1.0.0
#    restart: on-failure
    depends_on:
      - php
      - database
    ports:
      - target: 80
        published: 80
    volumes:
      - ./webserver/.deploy/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
      - ./api/public:/var/html/api:ro

  database:
    container_name: database
    image: webfux/mariadb:1.0.0
#    restart: on-failure
    env_file:
      - .env
    ports:
      - target: 3306
        published: 3366
        protocol: tcp
    volumes:
      # persist data (inside docker)
      - dbcontainer:/var/lib/mysql:rw
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

volumes:
  # persist data (inside docker)
  dbcontainer:
  shared-php-assets:
#  phpvendor: