api_platform:
    title: Webfux POC for API-Platform
    version: 1.0.0
    validator:
        # Enable the serialization of payload fields when a validation error is thrown.
        # If you want to serialize only some payload fields, define them like this: [ severity, anotherPayloadField ]
        serialize_payload_fields: []

        # To enable or disable query parameters validation on collection GET requests
        query_parameter_validation: true
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    mapping:
        paths:
            - '%kernel.project_dir%/src/ApiResource'
            - '%kernel.project_dir%/src/Entity'
    # Good cache defaults for REST APIs
    defaults:
        normalization_context:
            skip_null_values: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
