doctrine_migrations:
    # migration versions table
    storage:
        table_storage:
            table_name: doctrine_migration_versions

    # use default entity manager
    em: default

    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'

    # Run all migrations in a transaction.
    all_or_nothing: false
