ARG IMAGE_NAME
ARG IMAGE_TAG

FROM composer:2.0 as build-stage
WORKDIR /app
COPY composer.json ./composer.json
COPY composer.lock ./composer.lock

ENV COMPOSER_CACHE_DIR=/app/.cache/composer

RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist

FROM ${IMAGE_NAME}:${IMAGE_TAG}-xdebug as test-stage
WORKDIR /var/app

COPY --from=build-stage /app/vendor/ ./vendor
# need to copy whatever is needed for testing
COPY ./src ./src
COPY ./public ./public
COPY ./tests ./tests
COPY ./phpunit.xml* .

FROM ${IMAGE_NAME}:${IMAGE_TAG} as production
WORKDIR /var/app

COPY --from=build-stage /app/vendor/ ./vendor
COPY ./src ./src
COPY ./public ./public
