version: "3.4"

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        IMAGE_NAME: php
        IMAGE_TAG: 1.0.0
      target: production
    restart: on-failure
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 9000
