ARG IMAGE_NAME
ARG IMAGE_TAG

FROM ${IMAGE_NAME}:${IMAGE_TAG}

ARG WORK_DIR
WORKDIR ${WORK_DIR}
VOLUME ${WORK_DIR}/var/

ARG APP_ENV
ENV APP_ENV=${APP_ENV}
ENV BIN_DIR="/usr/local/bin"

##################################################################
# entry-point
COPY .deploy/script/docker-entrypoint.sh $BIN_DIR/docker-entrypoint
RUN chmod +x $BIN_DIR/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]
CMD ["php-fpm"]